# Generated by Django 2.2.2 on 2019-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='request_query',
            field=models.TextField(default=None),
        ),
    ]
